# Blog posts
query MyQuery {
  allContentfulBlogPosts {
    edges {
      node {
        title
        featured_image {
          fluid {
            srcSet
          }
        }
        body {
          body
        }
        createdAt(formatString: "DD MMM YYYY")
      }
    }
  }
}

# Heroes
query MyQuery {
  allContentfulHeroes {
    edges {
      node {
        identifier
        body {
          body
        }
      }
    }
  }
}

# Call to actions
query MyQuery {
  allContentfulCallToActions {
    edges {
      node {
        identifier
        headline
        body {
          body
        }
      }
    }
  }
}

# Projects
query MyQuery {
  allContentfulProjects {
    edges {
      node {
        title
        description {
          description
        }
        featured_image {
          fluid {
            srcSet
          }
        }
        case_study_images {
          fluid {
            srcSet
          }
        }
      }
    }
  }
}

# Social media
query MyQuery {
  allContentfulSocialMedia {
    edges {
      node {
        identifier
        body {
          body
        }
        account_username
      }
    }
  }
}
